### ISSUE TITLE
Numpy 1.18 compatibility

### ISSUE THREAD

**Issue by giovanni-mariano** [Radiation-Transport/iWW-GVR#4]
I would like to report that the tool is not compatible with the current version of numpy. Starting from numpy 1.18.0 the "num" parameter of linspace must be an integer:
https://numpy.org/devdocs/release/1.18.0-notes.html

It should be enough to replace num with int(num).

Best regards,
Giovanni Mariano

**Comment by Radiation-Transport** [comment]
Thanks Mariano for your feedback. We are going to have a look at it and come back shortly with a new version.

**Comment by Radiation-Transport** [comment]
Bug solved. Thanks @giovanni-mariano
